### ISSUE TITLE
Request for a better documentation

### ISSUE THREAD

**Issue by marcoautiero** [dhis2/capture-app#148]
It would be nice to have a better documentation on this project; the actual readme is the `create-react-app` documentation but it would be better to have more specific documentation of the project.

Maybe it's something that a main contributor can more easily do.

**Comment by Powell-v2** [comment]
Hello @marcoautiero,

It would be nice indeed! Do you have anything specific in mind? It could be a good starting point.

**Comment by marcoautiero** [comment]
@Powell-v2  well, actually I don't have any specific idea in mind, I just see that in this project there is a useless documentation (because it's not specific to the project).

What I can tell you is that I find difficulties to get oriented on where should I begin to setup an environment to work and contribute on this project as well as on the entire DHIS2 information system.

I see that DHIS2 has a huge set of repositiories but I miss the big picture (what's the main project and how projects are linked to each other) and, for every project (like capture-app) I don't see a proper documentation usefull for a developer to get started (kind of "these are the system requirements, install this, install that, run this and run that"). I would like to contribute to DHIS2 but I'm quite confused and disoriented :)

**Comment by Birkbjo** [comment]
Hello!

General documentation for the ecosystem is briefly described here: https://dhis2.nu/guides/00-getting-started. This is where we try to keep general documenation and blog articles about our infrastructure and processes. The developer portal should be more easily reachable, and is something we've recently discussed internally. Documentation for specific apps are generally very sparse, and is indeed something that should be improved upon. But hopefully the portal will give you a better overview of the system.

**Comment by Philip-Larsen-Donnelly** [comment]
Hi @marcoautiero!

historically, the app system documentation has been a bit separate from the app repositories. We plan to change that to some extent in the future, but until then I would also recommend that you start "one level up", following the link Birk provided above.

The platform and architecture has been evolving quite rapidly recently. We are trying to keep new documentation up-to-date as we go, but be aware that there is legacy documentation in many places that may be out-of-date, so it is also useful to get involved with the dhis2 developer community where you can ask questions and advice on current practices: https://community.dhis2.org/

If you have feedback or questions on some of the guides and materials that are available, don't hesitate to let us know!

**Comment by marcoautiero** [comment]
@Birkbjo @Philip-Larsen-Donnelly thank you!

I will read the linked doc, hopefully I will be able to propose you more specific idea about the documentation of capture-app (or other apps)

I appreciate the presence of a community on community.dhis2.org/ but I suggest you consider the idea to open a channel on slack open to anybody (actually the access to your slack workspace is available only to people with a @dhis2.org email address)
